all:
	g++ src/main.cpp src/Game.cpp src/GameStateStart.cpp src/GameStateEditor.cpp src/TextureManager.cpp \
	src/AnimationHandler.cpp src/Tile.cpp src/Map.cpp \
	-I include/ -I /opt/SFML-2.2/include/ -L /opt/SFML-2.2/lib -lsfml-graphics -lsfml-window -lsfml-system -L /opt/glew-1.10.0/lib -lGLEW -std=c++11 -o bin/CityBuilder
